README.md
Fixes the links of CODEOWNERS, because GitHub cannot parse the `@` at README.
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.
Make sure you had fun coding 🙃
=> Update the links of CODEOWNERS

metaseq/scripts/consolidate_fsdp_shards.py, projects/OPT/download_opt175b.md
Copy over the consolidation script for HF.
Used the script internally yesterday.
=> [checkpoint] Copy over consolidate script

metaseq/scripts/download_opt175b.sh
Fixes Issue #35.
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.
Make sure you had fun coding 🙃
=> script saves as pt files without api key at end

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/how-to-question.md, metaseq/scripts/reshard_mp.py, projects/OPT/download_opt175b.md
Some minor doc / template cleanup
=> Minor doc/string cleanups

metaseq/scripts/consolidate_fsdp_shards.py
Fix a small typo in copyright header
visual inspection
=> [Easy] fix copyright header

metaseq/data/monolingual_dataset.py, metaseq/data/token_block_dataset.py, metaseq/service/constants.py, metaseq/tasks/language_modeling.py, metaseq/tasks/language_modeling_inference_for_models_trained_with_streaming.py, metaseq/tasks/streaming_language_modeling.py, metaseq_cli/interactive_hosted.py
* Tackles https://github.com/facebookresearch/metaseq/issues/64
* Tackles `TODO(susanz): remove targets, given "future" being the only option in this codebase.`
=> Remove dict.txt dependency, and targets arg from LM tasks

README.md
Mention the community release front and center to point people to the most accessible place for inference.
Preview changes
=> Include HF Transfomers in README.

metaseq/tasks/streaming_finetune_language_modeling.py, metaseq/tasks/streaming_language_modeling.py
Add sampling from multiple corpora based on their size with a maximum size parameter as in Raffel et al., 2020, Wei et al., 2022, etc.
Test Plan
Tested with fine-tuning on various datasets with help from @qingliu1111
=> Add Example Proportional Sampling Maximum

projects/OPT/download_opt175b.md
Makes it easier to copy-paste when following the instructions
Closes https://github.com/facebookresearch/metaseq/issues/128
=> Add instructions to download the GPT2 asset files

metaseq/hub_utils.py
The prompt_len in current code relies on the batch_generator implementation and can easily introduce error. Remove that dependence in this PR. 
=> fix off by one in API

metaseq/distributed/utils.py, metaseq/service/constants.py, metaseq/service/responses.py, metaseq_cli/interactive_hosted.py
- Switch from copying to scratch with file utils to doing this entirely with an internal launch helper.
- Simplify the resulting logic.
**Testing Steps**
API is back up
=> [api] Simplify launch config.

metaseq/hub_utils.py, metaseq_cli/interactive_hosted.py
- Makes the API return error messages as JSON objects consistent with the OpenAI api
- More robust to hangs derived from a bad user supplied arg
- Adds support for setting `temperature=0` to get greedy.
Deployed and using it with various test cases.
=> [api] Support temp=0. Return errors as json.

metaseq/distributed/stitch_fsdp_ckpt.py
These changes just make the function `glue_megatron_parts ` to be more general `reshard_megatron_parts ` so that it can produce different model parts as output
=> added changes for resharding MP parts

CODEOWNERS, README.md
Ack for previous contributors too!
=> Updating codeowners to recent active users

README.md
Update the README with a small paragraph to link to the OPT-Alpa integration. The related issue is #176.
No test is needed in Metaseq.
=> [Community] Add OPT-Alpa integration

docs/api.md
Update `api.md` in `docs/` with a paragraph mentioning the OPT-Alpa integration. Otherwise, the FAQ there seems somewhat misleading. This is related to https://github.com/facebookresearch/metaseq/issues/176.
No test needed.
=> Update api.md to mention Alpa integration

metaseq/service/index.html, metaseq_cli/interactive_hosted.py
Previously, all API keys (including empty) would be accepted. Now we throw an authorization error if the user fails to provide one.
Also denylists a few placeholders that are in internal/external docs.
Manual testing
=> [api] API keys now required

README.md
We've added support for OPT-66B: https://huggingface.co/facebook/opt-66b
=> Update README in order to notify OPT66B availability on the Hugging Face Hub

.circleci/config.yml, gpu_tests/test_hf_compatibility.py, metaseq/distributed/stitch_fsdp_ckpt.py, metaseq/hub_utils.py, metaseq/scripts/convert_to_singleton.py
Fixing a bug in the convert to singleton script, and adding a test to verify that the conversion script works as intended, and the model outputs from a 125m singleton checkpoint are the same on metaseq and HF
Added integration tests
=> Convert to singleton bug fix + Test for singleton model compatibility between metaseq and HF

metaseq/hub_utils.py, metaseq_cli/interactive_hosted.py
Add a very important sync so that we don't worry about queuing future generations onto the GPU before old generations are done.
Looooots of debugging with @klshuster and @ngoyal2707.
=> [api] Add a clutch sync

.circleci/config.yml
Delete PyTorch 1.8 tests as we no longer plan to support it. Addresses #222. 
=> Removed Pytorch 1.8 tests

metaseq/trainer.py
Fix a small nit in the load_state_dict refactor code
I ran training, that loaded checkpoint with this small change turned on. Everything worked.
=> Fix Bug in Loading Checkpoint Post load_state_dict Refactor

metaseq/distributed/utils.py
Small change to ensure that distributed main returns value up the stack
=> distributed main returns value up call stack

gpu_tests/test_hf_compatibility.py
Owing to the changes in #264, there is now no longer a need to save the trimmed logits to an external file instead we could just return it directly. Also cleaned up a few unnecessary lines of code.
=> hf compatibility test returns value + cleanup

metaseq/scripts/reshard_model_parallel.py
Script for resharding a consolidated checkpoint into arbitrary model (tensor) parallel shards.
cc @ngoyal2707 who wrote it 😄
=> Reshard Model Parallel Script

metaseq/sequence_generator.py
=> Test code owners

.circleci/config.yml, setup.py
=> [ci] Upgrade black due to internal CI.

metaseq/tasks/streaming_language_modeling.py
Add support for other HF tokenizers for when we train our own.
Started training OPT baseline with new tokenizer.
=> [jsonl] Support other tokenizers.

metaseq/data/data_utils.py
Removed:
* infer_language_pair
* filter_by_size
* filter_paired_dataset_indices_by_size
* compute_mask_indices
* get_mem_usage
* lengths_to_padding_mask
* lengths_to_mask
=> [Cleanup] Remove unused methods in data_utils: 9/N

metaseq/trainer.py
Tackling https://github.com/facebookresearch/metaseq/issues/304
=> Remove train OOM recovery logic

metaseq/model_parallel/modules/transformer_layer.py, metaseq/models/transformer_lm.py, metaseq/modules/transformer_layer.py, metaseq/utils.py
Gives 2-3% speed up with almost no ppl loss, plus it is very hard to have correct bias gradients with sequence parallel + FSDP for now
=> added code to disable bias

CODEOWNERS, metaseq/hub_utils.py, metaseq/logging/meters.py, metaseq/logging/metrics.py, metaseq/model_parallel/criterions/vocab_parallel_cross_entropy.py, metaseq/model_parallel/modules/multihead_attention.py, metaseq/models/base_model.py, metaseq/sequence_generator.py, metaseq/tasks/streaming_finetune_language_modeling.py, metaseq_cli/train.py
- Tracks and plots validation accuracy for 2-way classification tasks during training
- Remove code owners for the opt_instruct branch
=> Validation accuracy during training

metaseq/data/iterators.py
Just making logging slightly more informative and slightly less annoying.
Training models incorporating this change.
=> [logging] Better dataloader logging

metaseq/hub_utils.py, metaseq/service/constants.py
changes for making interactive work without FSDP
=> changes for interactive to work with non-fsdp

metaseq/data/streaming_src_tgt_dataset.py, metaseq/logging/meters.py, metaseq/model_parallel/criterions/vocab_parallel_cross_entropy.py, metaseq/tasks/streaming_finetune_language_modeling.py, metaseq/tasks/streaming_language_modeling.py, metaseq_cli/train.py
Changes:
- remove sampling for validation splits
- update validation accuracy to support multi-label (previously we support only two-label tasks) during finetuning
=> multiclass val accuracy during finetuning

metaseq/dataclass/configs.py, metaseq_cli/train.py
Add option to run validation of checkpoint before any training or fine-tuning starts
=> add control option to turn on validation at step 0

metaseq/data/streaming_src_tgt_dataset.py, metaseq/tasks/streaming_finetune_language_modeling.py
- Add left or right truncation option for streaming_src_tgt_dataset module.
=> Add srctgt truncation

metaseq/logging/progress_bar/__init__.py, metaseq/logging/progress_bar/wandb_progress_bar.py, metaseq_cli/train.py
Offline wandb logging to the same folder as training logs
=> Offline wandb logging to the same folder as training logs

metaseq/model_parallel/modules/multihead_attention.py
We need Changes=true during training for doc attention to work. We need Changes=False during eval. This solves this using an environment variable called EVAL.
=> Changes flag

CODEOWNERS, README.md
Congrats! You now get spammed on all PRs here @davides ! 😄
=> Adding davides as codeowner

metaseq/model_parallel/models/transformer.py, metaseq/model_parallel/models/transformer_lm.py, metaseq/model_parallel/modules/transformer_layer.py, metaseq/models/base_decoder.py, metaseq/models/base_model.py, metaseq/models/incremental_decoder.py, metaseq/models/transformer_decoder.py, metaseq/models/transformer_lm.py, metaseq/modules/transformer_decoder_layer.py
Contains:
* https://github.com/facebookresearch/metaseq/pull/370
* https://github.com/facebookresearch/metaseq/pull/372
* and parts of https://github.com/facebookresearch/metaseq/pull/373
=> [Cleanup] Remove encoder inputs into decoder: 10.[4,5]

metaseq/model_parallel/modules/multihead_attention.py
After Victoria's PR, we don't need the EVAL flag anymore
=> Fix changes flag

metaseq/checkpoint_utils.py
Improving logging for checkpoint loading
=> Opt instruct fix checkpoint loading error logging

metaseq/models/base_decoder.py, metaseq/models/base_model.py, metaseq/modules/learned_positional_embedding.py, metaseq/modules/multihead_attention.py, metaseq/modules/sinusoidal_positional_embedding.py, metaseq/modules/transformer_decoder_layer.py, metaseq/utils.py
Remove references to onnx trace and export
=> [Cleanup] Remove onnx trace 

metaseq/modules/multihead_attention.py
Remove `apply_sparse_mask` method which currently is a noop.
=> [Cleanup] Remove noop apply_sparse_mask

gpu_tests/test_hub_utils.py, metaseq/hub_utils.py, metaseq/models/base_model.py
=> [Cleanup] Remove unused moe_disable_padding arg

metaseq/data/iterators.py
The worker in the dataloader tells its ID to the training process so that it can keep a count of how many sentences each worker has processed and which worker is next. However, worker IDs have to be rotated using worker_offset on restart. This offset was not added to the ID in this case.
TODO: make a test with a repro, which will require these steps
* Train normally, and checkpoint at a step that is not divisible by num_workers
* checkpoint
* Resume and train for a number of steps that is not divisible by num_workers
* checkpoint
* Resume (old code will resume with the wrong worker)
=> Fix bug in accounting for data loaders

cpu_tests/test_streaming_iterators.py, metaseq/data/iterators.py, metaseq/tasks/streaming_language_modeling.py
This tests the change to worker offset (also small fix to the previous patch where a % was missing)
=> add a double restart data loader test

CODEOWNERS, README.md
=> Adding Igor as codeowner

metaseq/hub_utils.py
t is a tensor, and t in set() does not work. The correct way is to use t.item().
=> Fix stopping during generation

.circleci/config.yml, gpu_tests/test_checkpoint_saving.py, metaseq/model_parallel/criterions/vocab_parallel_cross_entropy.py, metaseq/model_parallel/models/transformer.py, metaseq/models/transformer_decoder.py, metaseq/modules/feedforward_network.py, metaseq/modules/fused_bias_gelu.py, metaseq/modules/transformer_decoder_layer.py, metaseq/modules/transformer_encoder_layer.py
updated to megatron_v3 without seq_parallel for now.
will send a separate PR for that once this lands
=> changes for updating to megatron brnach fairseq_v3

gpu_tests/test_checkpoint_saving.py, metaseq/cli/train.py
=> Reenable test_checkpoint_saving.py

metaseq/model_parallel/modules/multihead_attention.py, metaseq/model_parallel/modules/transformer_layer.py, metaseq/models/transformer_lm.py, metaseq/modules/transformer_decoder_layer.py
To scale fc2 in FFN and out_proj in MHA with.
=> Add full_megatron_init_scalar flag

metaseq/tasks/language_modeling.py
Support unified tokenizer file in language modeling task. This is required for running evals...
CircleCI tests
=> Support unified tokenizer file in language modeling task

metaseq/distributed/__init__.py, metaseq/distributed/rendezvous.py, metaseq/distributed/utils.py
The PyTorch TCP rendezvous seems to have trouble if there are minor network blips, causing troubles in getting past initialization at sufficient scale. This patch introduces a custom rendezvous method which copy-pastes much of the pytorch code, and adds a simple retry loop around it.
Ongoing
=> [distributed] Custom rendezvous

metaseq/model_parallel/models/transformer_lm.py, metaseq/model_parallel/modules/sequence_parallel_transformer_layer.py, metaseq/modules/activation_functions.py, metaseq/modules/transformer_decoder_layer.py
=> Adding relu for seq par

metaseq/model_parallel/modules/multihead_attention.py, metaseq/model_parallel/modules/transformer_layer.py, metaseq/models/transformer_decoder.py, metaseq/models/transformer_lm.py, metaseq/modules/positional_embedding.py, metaseq/modules/transformer_decoder_layer.py, metaseq/utils.py
=> Truncate normal init

metaseq/tasks/streaming_language_modeling.py
PER BENCHMARK PROPORTIONS
--data-sampling-prob '{"flan": 0.35, "ni_v2": 0.24, "exmix": 0.03, "crossfit": 0.03, "pretrain": 0.0, "cot": 0.02, "t5": 0.03, "promptsource": 0.28, "unified_skg": 0.02,}'
- You don't need to specify probs for all benchmarks. The code will uniformly distribute the remaining prob mass amongst the rest of the benchmarks. So, you can specify just --data-sampling-prob '{"pretrain": 0.0}'
- The logs print the before proportions, and the after proportions, which you can double check.
EQUALIZE CLUSTER PROPORTIONS AFTER APPLYING BENCHMARK PROPS
--equalize-cluster-probs
This will equalize the prob of each cluster within a benchmark. Note that this needs cluster names to be included in the dataset names.
PROVIDE PER BENCHMARK EPS
--caps '{"flan": 30000, "ni_v2": 5000, …
=> Add data proportions

metaseq/cli/train.py
Tested on a small run - finally a quiet stderr!
=> Suppress pytorch spam

gpu_tests/test_checkpoint_saving.py, metaseq/checkpoint_utils.py, metaseq/cli/train.py, metaseq/dataclass/configs.py, metaseq/hub_utils.py, metaseq/trainer.py
Tested with small run with nfs:// upload path, confirmed two sets of checkpoints saved without issue.
=> [Cleanup] Checkpoint saving cruft

metaseq/cli/interactive_cli.py, metaseq/cli/interactive_hosted.py, metaseq/hub_utils.py, metaseq/service/constants.py
Upstream sequence parallelism changes to main branch. (See #537) for details on the change
=> Support overriding sequence parallelism in the API (#537)

Dockerfile, metaseq/service/constants.py
This flag was removed, I missed this change.
=> remove nbest from constants file

metaseq/trainer.py
Shift the ratio calculation to be before ewm is updated.
=> Compute ratio to existing ewm

metaseq/data/iterators.py, metaseq/tasks/__init__.py, metaseq/tasks/streaming_language_modeling.py, metaseq_cli/train.py
Add update_freq to streaming_language_modeling to possibly increase 175B model training size.
=> hack update_freq implementation for streaming_language_modeling

metaseq/cli/train.py, metaseq/dataclass/configs.py
Based on https://github.com/facebookresearch/metaseq/pull/500
that version was triggering model save every update.
=> added way to skip batches based on Peters previous PR

metaseq/cli/train.py, metaseq/dataclass/configs.py
=> Bigbig update

CODEOWNERS
Add @sharannarang to CODEOWNERS
n/a
=> Add Sharan to CODEOWNERS

metaseq/model_parallel/models/transformer_lm.py, metaseq/models/transformer_decoder.py, metaseq/models/transformer_lm.py, metaseq/modules/positional_embedding.py, metaseq/utils.py
* Flag for scaling positional embedding init
* Truncate init for embeddings too
* Enable zeros init if sigma is small enough
=> Initialization changes

metaseq/distributed/rendezvous.py
Flagged for failing OSS requirements
=> Add copyright header

projects/OPT-IML/README.md
=> Add OPT-IML 175B request form

metaseq/utils.py
Tiny PR to remove two unused methods
=> rm load_align_dict and strip_pad methods

gpu_tests/test_checkpoint_saving.py, metaseq/checkpoint_utils.py, metaseq/cli/train.py, metaseq/data/iterators.py, metaseq/dataclass/configs.py, metaseq/trainer.py
Cherry-picked from bigbig:
* c9e7c3dde60c6fb04c35dca73aa4820e819311f7
* 0bbc1707d1041c21f4b93202a1804fa8e1be6d4f
* e58a7ac6bcf1839f7b3606bd999337b890d6f564
* 1caeff099c33c2a225ef671863e88073a8b97077
=> Merge bigbig branch changes into main

metaseq/model_parallel/models/transformer_lm.py, metaseq/models/transformer_decoder.py, metaseq/models/transformer_lm.py, metaseq/modules/positional_embedding.py, metaseq/utils.py
Or use `susan/dec15_30b_init_angel` branch
=> Cherrypicking pos-init-scalar from main

metaseq/data/data_utils.py, metaseq/dataclass/configs.py, metaseq/models/ema/ema.py, metaseq/modules/adaptive_softmax.py, metaseq/sequence_generator.py, metaseq/trainer.py
=> Add EnsembleModel/EnsembleModelWithAlignment

preprocessing/README.md, preprocessing/books3/README.md, preprocessing/books3/build.sbt, preprocessing/books3/project/ProjectDependencies.scala, preprocessing/books3/project/build.properties, preprocessing/books3/src/main/scala/BooksDedup.scala, preprocessing/books3/src/main/scala/BooksFooterCleaner.scala, preprocessing/books3/src/main/scala/BooksHeaderCleaner.scala
Original source: https://github.com/fairinternal/fairspark/pull/45/files
=> Books3 processing

cpu_tests/test_cm3_dataset.py, metaseq/data/__init__.py, metaseq/data/cm3_dataset.py, metaseq/tasks/streaming_language_modeling.py
**Implements the CM3 and FIM Objective**
This was ported from the old cm3 branch which has been used for a couple of projects now. I've explicitly added support for FIM (which is a special case of CM3).
I've added a couple of tests (although I should probably add some more). I'm running a couple trainings right now to make sure both FIM and CM3 (with original Poisson parameterization) work as expected.
Fixes Issue #632
=> Implement CM3/FIM Objective

CODEOWNERS, README.md
=> Adding Uriel back as codeowner

metaseq/sequence_generator.py
1. Fix last step in decoding. Updated with main. See details in PR: https://github.com/facebookresearch/metaseq/pull/657
2. Fix top-p sampling. The below error happens when`lprobs` (the model's log-probabilities over the vocabulary at the current step) have all entries of `-inf`. Similar issue as in this PR: https://github.com/huggingface/transformers/issues/15169 
```
File "/private/home/ems/GitHub/facebookresearch/metaseq/metaseq/sequence_generator.py", line 423, in _sample_topp
choices = torch.multinomial(trunc_sprobs, 1)[:, 0]
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```
=> Fix decoding last step and inf during sample topp

docs/training.md
=> Fix training script command in Readme

metaseq/checkpoint_utils.py
Hitting:
```
RuntimeError: trying to restart a job that already wrote checkpoint_last
```
with current run using NFS. Skipping checkpoint_last from list of candidates to consider when restarting an existing run.
=> Ignore checkpoint_last restart with NFS

setup.py
upgrading flask due to https://github.com/facebookresearch/metaseq/security/dependabot/3
=> upgrade flask

metaseq/cli/train.py
Always enable post_checkpoint_callback and added support for local symlink.
=> Enable post ckpt callback, support local symlink
