- metaseq/scripts/reshard_mp_launch.sh
In the shard script, it incorrectly pointed to `metaseq_internal` instead of `metaseq` as the location of the `reshard_mp` file.
I tested my change by sharding the 175b file with the modified script.
> changed metaseq_internal to metaseq

- .github/ISSUE_TEMPLATE/bug_report.md
Closing #42 
I have added two OSs in the OS section in `bug_report.md`.
> included two OSs in bug_report

- metaseq/launcher/slurm.py
Hi there, thanks for your great work!
I found that there is no quote for `train_cmd` in `metaseq/launcher/slurm.py`.
It leads to an issue that `dry-run` prints a command without quote, namely `--adam-betas (0.9, 0.95)`, which could not run directly. The correct command should be `--adam-betas '(0.9, 0.95)'`.
Add quote for `train_cmd` in the function `gen_train_command` of `metaseq/launcher/slurm.py`.
The command `--adam-betas (0.9, 0.95)` will be fixed to `--adam-betas '(0.9, 0.95)'` in this PR : )
Run the following command to print the `dry-run` message.
```bash
opt-baselines \
-n 1 -g 2 \
-p test_v0 \
--model-size 125m \
--azure \
--data ./dataset \
--checkpoints-dir "./outputs" \
--local \
--dry-run
```
> [Bug Fixed] Add quote for `train_cmd` in `metaseq/launcher/slurm.py`

- metaseq/distributed/utils.py
- metaseq/hub_utils.py
- metaseq_cli/interactive_cli.py
Adds support for CLI interactive.
This involves a major change to distributed initialization, which I copied from ParlAI: Instead of having the main process spawn N subprocesses all running the distributed code, and then idle until they wrap up, we have it spawn N-1 processes and then we also run the distributed code on the main process.
This means that exceptions or signals like KeyboardInterrupts in the main thread can be caught and propagated to the spawns to be terminated. It also means we don't need to do any hacks to reroute stdin/stdout in the rank0 process.
Also tested that I can cleanly ctrl-c now, and also several exceptions due to standard iterations were correctly propagated.
> CLI interactive

- metaseq/launcher/slurm.py
opt-baseline training broke with this PR. Reverting.
The dry-run fix should be a fix in the dry-run codepath, not one that universally applies addition quotes to all args for slurm launch.
> Revert "add quote for train_cmd (#44)"

- metaseq/scripts/convert_to_singleton.py
- Related to: #60 
`convert_to_singleton.py` doesn't seem to recusively unwrap fully sharded modules, leaving with the following parameters in `restored.pt` (notice the `flat_param` substring):
```python
{'decoder.embed_positions.weight': torch.Size([2050, 2048]), 'decoder.embed_tokens.weight': torch.Size([50272, 2048]), 'decoder.layer_norm.bias': torch.Size([2048]), 'decoder.layer_norm.weight': torch.Size([2048]), 'decoder.layers.0.flat_param_0': torch.Size([25185280]), 'decoder.layers.1.flat_param_0': torch.Size([25185280]), 'decoder.layers.10.flat_param_0': torch.Size([25185280]), 'decoder.layers.11.flat_param_0': torch.Size([25185280]), 'decoder.layers.12.flat_param_0': torch.Size([25185280]), 'decoder.layers.13.flat_param_0': …
```
> Recursively unwrap fully sharded model in `convert_to_singleton.py`

- projects/OPT/download_opt175b.md
This commit updates the documentation for downloading the OPT-175B parameters with the space required to store all of the files. This is super helpful for any practitioner planning to actually download the data.
Considerations before submitting:
- [-] Was this discussed/approved via a Github issue?
> [Docs Only] Update Documentation to Include Required Storage Space

- metaseq/distributed/utils.py
Fixes an off-by-one in #48 that was causing jobs launched outside-slurm environments to fail. This also fixes #70.
Identified this when testing #60 after I merged master into it.
> [bug] Broken local spawning on all scripts

- metaseq/data/__init__.py
- metaseq/data/streaming_src_tgt_dataset.py
- metaseq/model_parallel/criterions/vocab_parallel_cross_entropy.py
- metaseq/tasks/streaming_finetune_language_modeling.py
- metaseq/tasks/streaming_language_modeling.py
**Description:**
This diff allows us to backpropagate losses only on designated target tokens rather than all the input tokens. It introduces a new jsonl data format for this, where "src" and "tgt" keys are specified. To use this, use the streaming_finetune_language_modeling task. The task concatenates the src and the tgt, and is trained to produce this autoregressively, but only takes losses on the tgt tokens into account. This is particularly useful during fine-tuning.
**Test plan**
1. Does not change existing pre-training i.e. tested existing pre-training on 125M model and ppl for the first 5 updates were exactly the same i.e. unchanged.
2. Works successfully on src-tgt-format without crashing and performs competitively on copa from superglue.
> Finetune only on target labels

- .github/workflows/lint.yml
- mypy.ini
- setup.py
PR for [issue 14](https://github.com/facebookresearch/metaseq/issues/14).
Here we add MyPy to CI.
Run `mypy` at local laptop & run the check via an actual pull request.
> Add MyPy to CI

- metaseq/scripts/download_opt175b.sh
- projects/OPT/download_opt175b.md
Minor modification to the 175B download script to allow the user to download the files into a directory other than the one that the command is being run from.
I ran it.
> Allow downloading to a target directory

- metaseq/dataclass/configs.py
- metaseq/optim/dynamic_loss_scaler.py
- metaseq/optim/fp16_optimizer.py
- metaseq/trainer.py
* Set hard defaults for loss scaler logic (no longer a function of data parallelism)
* Scale scale window with loss scale
* Remove raising FloatingPointError when min loss scale is reached - just continue skipping gradients (using external monitoring to restart)
> Dynamic loss scaler changes for 66b

- setup.py
* Resolves https://github.com/facebookresearch/metaseq/issues/55#issuecomment-1135353598
* Avoids https://github.com/facebookresearch/metaseq/pull/124
> Pin omegaconf to 2.1.1, tensorboard to 2.8.0

- Dockerfile
- setup.py
Hi, the current Dockerfile cannot build successfully, I made a few fix for it. 
1.  Limit the max version for hydra-core, since hydra-core 1.2 will require omegaconf~=2.2 and raise a conflict.
2. Fix error in line 35.
3. I didn't encounter issue https://github.com/NVIDIA/nvidia-docker/issues/1631, and the workaround in line 8-9 raises an file not found error for me. They have probably fixed the docker, but I am not sure about this.
docker build -f Dockerfile .
> Fix errors when build docker

- metaseq/data/streaming_src_tgt_dataset.py
- metaseq/tasks/streaming_language_modeling.py
Description:
Currently, multiple examples are packed into a single sequence during training/fine-tuning and attention can happen across sequences. This diff adds eos mode, which uses a single example per sequence. This can be useful for fine-tuning/debugging. 
Test Plan:
Code path is executed via --break-mode eos_pad_8 and code has been tested earlier in a private branch.
> Add eos mode for src tgt dataset

- projects/OPT/download_opt175b.md
It might be easier to manually checksum 8 files rather than 992 of them. So I am copying from [this comment](https://github.com/facebookresearch/metaseq/issues/81#issuecomment-1122617595) by Stephen and put it into the docs.
Including the gpt2 files checksum is also useful as a sanity check, as the files could be corrupted during download (or people like me who don't read the instruction and download the wrong ones).
Related: https://github.com/facebookresearch/metaseq/pull/138
> Add a 2nd md5sum check after consolidating the shards

- metaseq/logging/progress_bar/__init__.py
Change the progress bar creation logic so that only one of `WandBProgressBarWrapper` and `TensorboardProgressBarWrapper` is called. Calling these two wrappers sequentially will result in an exception.
> Fix progress bar exception when both tensorboard and wandb are turned on

- metaseq/dataclass/constants.py
- metaseq/model_parallel/modules/multihead_attention.py
- metaseq/models/transformer.py
- metaseq/models/transformer_lm.py
We are trying to optimize model training by having document level attention. What this entails is that we modify the attention mask to just attend to tokens in the current document, as opposed to having a constant triangular (causal) attention mask. The goal here is to ensure that tokens don't attend across documents.
To accomplish this, we
1. Change the constant upper triangular mask to depend on the data separator tokens, specified by the `self_attn_doc_sep` field
2. Reset the positional encoding at the end of each document.
Consider a list of 20 documents. We consider the following two cases - 
1. Passing the documents, one per sequence, in a batch of 20 sequences. No special attention mask is used, we still use the upper triangular mask.
2. …
> Support document level attention while training model parallel models

- metaseq/file_io.py
Without this `gpt3_eval` hits the following exception:
```
NameError: name 'Namespace' is not defined
```
> Add missing Namespace import

- metaseq/hub_utils.py
- metaseq/search.py
- metaseq/sequence_generator.py
For a few weeks now, the API has consistently assigned the first logit after the prompt to be positive, which makes it an invalid probability.
Digging into it, it's because beam search keeps track of cumulative NLL (which makes sense for beam search). However, the first step of the beam search was being provided logits only for the newest token. As a result, the cumulative logit logic was assigning a "reset to 0" offset on the first one.
While this is a little bit kludgy, adding in a new one-time-only parameter, it's the best way to provide this information to the search algorithm without gutting it all.
This also makes the writing into the scores slightly more compact.
Note that generations do not change compared to previously. Just the bookkeeping of logits. …
> [api] Fix singular positive logit

- metaseq/scripts/convert_to_singleton.py
Bug fix for convert_to_singleton.py - using reshard_megatron_parts instead of glue_megatron_parts after changes in #169 
```
ls -a 125m/
.  ..  dict.txt  gpt2-merges.txt  gpt2-vocab.json  reshard-model_part-0.pt  reshard-model_part-1.pt
```
```
python -m metaseq.scripts.convert_to_singleton 125m
['--model-parallel-size', '2', '--distributed-world-size', '2', '--task', 'language_modeling', '--bpe-merges', '125m/gpt2-merges.txt', '--merges-filename', '125m/gpt2-merges.txt', '--bpe-vocab', '125m/gpt2-vocab.json', '--vocab-filename', '125m/gpt2-vocab.json', '--bpe', 'hf_byte_bpe', '--path', '125m/reshard.pt', '--checkpoint-shard-count', '1', '--use-sharded-state', '125m']
2022-07-06 20:24:19 | INFO | metaseq.distributed.utils | distributed init (rank …
```
> Using reshard_megatron_parts instead of glue_megatron_parts after changes in #169

- metaseq/service/constants.py
- metaseq_cli/interactive_hosted.py
- Have a maximum beam size to avoid OOM
- Propagate CUDA crashes to be hard crashes, rather than reported to the user.
Not yet tested.
> [api] Small robustness improvements.

- metaseq/data/jsonl_dataset.py
As a mild convenience, we want the indices of datasets to be built automatically when they're first used. However, if we build them on every worker, we can easily flood NFS and the process is slow. However, if we build them on the primary worker, then it only takes a couple minutes to handle several TB.
This PR causes the indexes to be built on the main worker, while the rest take a break.
Used in internal ablation
> [jsonl] Build cache on main worker only.

- cpu_tests/test_jsonl_dataset.py
- metaseq/data/jsonl_dataset.py
Added code to check for validity of json in jsonl files in the index building function. Also added two new tests to make sure that empty jsonl files as well as corrupt jsonl files throw up the right errors.
ran the new tests to ensure that it works as expected
> Better validation in JSONL datasets

- metaseq_cli/interactive_hosted.py
Bug in the queuing logic means that we actually are grouping generations that we shouldn't.
Manual testing.
> [api] Prevent unlike generations from being grouped.

- metaseq/checkpoint_utils.py
- metaseq/criterions/cross_entropy.py
- metaseq/distributed/fully_sharded_data_parallel.py
- metaseq/distributed/stitch_fsdp_ckpt.py
- metaseq/models/base_decoder.py
- metaseq/models/base_encoder.py
- metaseq/models/base_model.py
- metaseq/models/transformer.py
- metaseq/sequence_generator.py
- metaseq/sequence_scorer.py
- tests/utils.py
Following https://github.com/facebookresearch/metaseq/pull/229 and continuing to break down https://github.com/facebookresearch/metaseq/pull/197.
Remove:
* unused `handle_legacy_ln_` method
* unused `reorder_encoder_out` method
* unused `net_outputs` arg in `get_targets`
* redundant `load_state_dict` method (previously needed to override given the added step of "upgrade state dict" to be backwards compatible)
* unused `Namespace` import
* unused `sample` arg from `get_normalized_probs_scriptable` and `get_normalized_probs` methods
> [Cleanup] Delete unused methods / imports / args: 1/N

- metaseq_cli/interactive_hosted.py
In #227, we fixed a bug causing unlike-workloads to be batched together, but introduced another. Without resetting the queue outside the if statement, whichever queue was last served would continue to be held onto until work was submitted to it. As a result, no work would be accomplished until someone _happened_ to ask for a generation of that same form.
This fixes our idle loop.
Deployed a couple days now.
> [api] Fix worker queue logic

- metaseq/checkpoint_utils.py
When downloading checkpoints from blob, we have a race condition where not all checkpoints may have finished downloading to local workers, thus causing an exception. This ensures everyone patiently waits on everyone else.
cm3 branch
> [checkpoint] Fix race condition with blob.

- metaseq/hub_utils.py
- metaseq/sequence_generator.py
- metaseq/service/constants.py
@tbmihailov pointed out that our logits differ from the openai's, in that we (previously) started our logprobs with the first generated token, rather than including a sentinel `null` logprob and including the first token.
This PR fixes that so we are more consistent with OpenAI
So much manual testing.
> [api] Fix logit outputs

- metaseq/models/transformer.py
- metaseq/modules/transformer_layer.py
Continuing the breakdown of https://github.com/facebookresearch/metaseq/pull/197
Remove:
* unused `full_context_alignment` arg (always kept as `False`)
* unused `alignment_heads` arg (default all heads)
* unused `char_inputs` arg (controls an `export` flag that isn't ever used)
* unused `alignment_layer` arg (default is always last layer)
> [Cleanup] Delete unused args: 3/N

- metaseq/model_parallel/modules/transformer_layer.py
- metaseq/models/transformer_lm.py
- metaseq/modules/layer_norm.py
- metaseq/modules/transformer_layer.py
Continuing to break down https://github.com/facebookresearch/metaseq/pull/197
* Removed `scale_fc`, `scale_attn`, and `scale_heads` flags that were brought in as part of Normformer - might have to bring scale_fc back later, but hoping to clean up configuration / flags before then.
* Removed `sync_ln_variance` which was brought in to speed up NormFormer when we went tensor parallel.
> [Cleanup] Delete unused args - NormFormer: 4/N

- metaseq/model_parallel/modules/transformer_layer.py
- metaseq/models/transformer_lm.py
- metaseq/optim/adam.py
- metaseq/trainer.py
Continuing to break down https://github.com/facebookresearch/metaseq/pull/197
(Base branch will switch/be rebased to main once https://github.com/facebookresearch/metaseq/pull/251 is merged)
Removing Adam8bit and stable-emb/block-wise flags which were brought in together in https://github.com/fairinternal/fairseq-py/pull/2063 .
> [Cleanup] Delete unused args / classes - Adam8Bit: 5/N

- metaseq/criterions/cross_entropy.py
- metaseq/models/base_decoder.py
- metaseq/sequence_generator.py
- metaseq/sequence_scorer.py
- tests/utils.py
This patch keeps our logit scores in fp32 so they are more accurately reported to the user. Has the nice added benefit of fixing a known bug where using temperature 0.1 causes overflow issues.
@tbmihailov running evals on this
> [api] Keep logits in fp32

- metaseq/file_io.py
There's a known bug where training on bf16 and then requeuing will result in the model temporarily being converted to fp16, causing potential noise issues. This avoids this conversion.
This likely explains why some users are seeing some loss explosions after they requeue.
Launched the API and manually checked the code path taken.
> [bf16] Don't convert weights to fp16 during load

- metaseq/file_io.py
PR(https://github.com/facebookresearch/metaseq/pull/254) broke loading of old OPT model, this commit fixs it. 
> fixing opt loading

- metaseq/scripts/generation_benchmarks.py
Added a script that takes in one/many model sizes as input and outputs generation statistics. Addresses #220. Also allows for custom data to be passed as input. 
Run this with multiple model sizes to observe WPS counts. Can take multiple models as input and report output for each.
Usage : 
` python generation_benchmarks.py --model_name 2.7b 13b --padding_size 32`
NB: model checkpoint sizes for 66b are huge and the script will require sufficient storage and time tor run.
> Add script to measure generation benchmarks for different models sizes

- gpu_tests/test_hf_compatibility.py
- metaseq/file_io.py
- metaseq/hub_utils.py
- metaseq/scripts/convert_to_singleton.py
- metaseq/scripts/reshard_mp.py
Fixing [issue #276](https://github.com/facebookresearch/metaseq/issues/276). Converting model data type when loading states is dangerous. Our model is saved as it is trained, so there is no need to further change the datatype when loading correctly saved models . 
> loading model as it is trained

- metaseq/models/transformer.py
Moved the future mask to CUDA so that all operations for document attention also take place on CUDA. Refer to issue #285 for context. The speedup offered by this is marginal but over multiple runs may cumulate.
To test, I set attn doc seperator to a random number to trigger the code to enter the branch, and timed it using the methods used in #220. Observed that over 436 calls to the function on CPU it takes 0.42 seconds vs 0.09 seconds on GPU.
> moving future_mask to cuda for document attenion

- metaseq/launcher/opt_baselines.py
`metaseq.launcher.opt_baselines`'s `--benchmark` option seems to be broken by this commit 1d2d15255db8c5f51165108e53bc40ecb00b73fe
```
$ python -m metaseq.launcher.opt_baselines --model-size 8m --benchmark -t 1 -g 8 -n 1 -p test-8m1 --azure 
Traceback (most recent call last):
File "/shared/home/jieru/miniconda3/envs/fairseq-20220503/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/shared/home/jieru/miniconda3/envs/fairseq-20220503/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/shared/home/jieru/fork/metaseq/metaseq/launcher/opt_baselines.py", line 342, in <module>
cli_main()
File "/shared/home/jieru/fork/metaseq/metaseq/launcher/opt_baselines.py", line 336, in …
```
> fix --benchmark option

- metaseq/benchmark/dummy_lm.py
Right now, the dummy lm batch size for validation is quite large (same as the training set). It takes a long while to step through, especially when there are multiple validation shards.
This patch shrinks the valid/test sets to a single batch. Additionally, makes the dataset aware of `--batch-size-valid`.
Manual testing
> [dummy_lm] Make validation size smaller.

- metaseq/checkpoint_utils.py
- metaseq/launcher/opt_baselines.py
thanks @stephenroller for the pointer!
Skip saving the checkpoints in when benchmarking
tested by running a tiny benchmark
```
python -m metaseq.launcher.opt_baselines --model-size 8m --benchmark -t 1 -g 8 -n 1 -p test-8m --azure
```
verified in `train.log`
```
2022-08-09 23:47:29 | INFO | metaseq.checkpoint_utils | Not saving checkpoints.
```
changed to warning
```
2022-08-10 00:09:03 | WARNING | metaseq.checkpoint_utils | Not saving checkpoints.
```
> Do not save checkpoint in benchmark mode

- metaseq/launcher/opt_baselines.py
fix #287 
When I test training code and enabled benchmarking, it will throw `valid_subsets` referenced before assignment error
Command:
```
opt-baselines -n 1 -g 8 -p test_v0 --model-size 125m --aws --benchmark --checkpoints-dir /fsx/metaseq_models/ --no-save-dir
```
Error:
```
4:     hyperparam("--valid-subset", ",".join(f"valid/{ss}" for ss in valid_subsets)),
4: UnboundLocalError
4: : local variable 'valid_subsets' referenced before assignment
```
After this fix works fine with `--benchmark` argument
Considerations before submitting:
-->
> fix valid subset when benchmarking

- metaseq/dataclass/configs.py
- metaseq/tasks/streaming_language_modeling.py
- metaseq/trainer.py
These metrics have been clogging our stderr, but they're no longer relevant to us: pnorm/gnorm/etc all getting to zero is an artifact of fp16 having a very poor range for [xmins](https://nhigham.com/2018/12/03/half-precision-arithmetic-fp16-versus-bfloat16/). While this was important (and harrowing) to track before, the switch to bfloat16 has eliminated this concern for us.
`2022-08-20 12:47:21 | INFO | train_inner | {"epoch": 1, "actv_norm": "937.49", "pos_norm": "0.701", "tok_norm": "1", "emb_norm": "0.008", "docsperex": "3.82", "loss": "10.436", "ppl": "1385.32", "wps": "419672", "ups": "0.4", "wpb": "1.04858e+06", "bsz": "512", "num_updates": "293", "lr": "9.84874e-05", "gnorm": "1.139", "clip": "100", "train_wall": "2", "cuda_gb_allocated": …
> [metrics] Stop logging pnorm etc.

- metaseq/dataclass/configs.py
- metaseq/tasks/streaming_language_modeling.py
- metaseq/trainer.py
#189 added support for subshards, which is important for creating smaller shards (virtually) and allowing faster rewinding of dataloaders. However, subshard values that are reasonable for training (e.g. 50) are not reasonable for validation, as the validation set is much smaller.
This patch makes it so subshards are only enabled in training, and ignored elsewhere.
Ran a training run with `--data-subshard-count 50`
> [LM] Remove subshards on validation.

- metaseq/distributed/utils.py
Small QOL change. Adds a new log line saying the full nodelist in SLURM format.
Also silence some torch.distributed log lines.
Internal training launch. Initialization now looks like this (with other internal change):
```
commit 380d8bc41351410399797f7e68fbe005acdaa4f2
Submitted batch job 82764
2022-08-05 08:44:41 | INFO | metaseq.distributed.utils | initialized host fairwus3-1-htc-337 as rank 0
2022-08-05 08:44:41 | INFO | metaseq.distributed.utils | initialized host fairwus3-1-htc-339 as rank 16
2022-08-05 08:44:41 | INFO | metaseq.distributed.utils | initialized host fairwus3-1-htc-339 as rank 23
2022-08-05 08:44:41 | INFO | metaseq.distributed.utils | initialized host fairwus3-1-htc-339 as rank 21
2022-08-05 08:44:41 | INFO | …
```
> [QOL] Log the nodelist.

- metaseq_cli/train.py
When initiating a training run, dump a copy of the config in the same folder as the checkpoints and logs.
Manual testing.
> [QOL] Save the training config in the checkpoint dir.

- metaseq/trainer.py
See title. Not called anywhere (all replaced by metrics.get_meter(s))
> [Cleanup] Remove deprecated Trainer.get_meter: 8/N

- metaseq/launcher/opt_baselines.py
Brittle logic here, but valid subset currently exists if `args.data` is not None (as in, `args.data` is only None when `args.benchmark` is set ). Without this fix, throws:
```
File "/shared/home/susanz/repos/metaseq/slurm_snapshot_code_oss/2022-08-20T22_54_06.361518/metaseq/tasks/streaming_language_modeling.py", line 275, in get_shard_str
int(shard_id) not in shards
ValueError: invalid literal for int() with base 10: 'BookCorpusFair'
```
> Fix inclusion of valid subset in opt-baseline

- metaseq_cli/train.py
There's an annoying extra tensorboard created from logging average train metrics over the epoch. It's not useful and just creates extra noise.
Training models including this change
> [tboard, QOL] Don't log average train metrics.

- metaseq/dataclass/configs.py
- metaseq_cli/train.py
Our current logic always validates and saves at the end of an epoch, even when we set flags such that it isn't supposed to. This is because we ignored the "no_epoch_checkpoints" flag, and because the "validate_interval" flag made it impossible (as it's an interval of epochs). I've killed the validate_interval flag and updated the logic appropriately.
Been training with this patch.
> [checkpoints] Don't validate/save after epochs.

- metaseq/checkpoint_utils.py
THIS DEPENDS ON METASEQ-INTERNAL CHANGES.
Right now our checkpoint files have this format:
`checkpoint_7_5500.pt` where `7` is the "epoch" number (for our weird definition of epoch). This is rather annoying when you're _searching_ for a particular checkpoint, as I know I want update 5500, but I have no idea what the epoch number should be. This is made worse with Blob store, which can't handle wildcards in the middle of strings.
This patch changes the format to:
`checkpoint_5500.pt`, stripping the epoch number.
My latest checkpoints trained with this!
> [cleanup] Update some f-strings, change checkpoint naming scheme.

- metaseq/optim/fp16_optimizer.py
- metaseq/trainer.py
when not in FSDP, the model wasn't converted to bf16 although bf16 was set to True.
In MemoryEfficientFP16Optimizer.zero_grad (that is applied every training step), the model sets  _multiply_factor back to 1.0:
https://github.com/facebookresearch/metaseq/blob/bbcedfebb4c35f71cdda1f1a358491f3996a9fc3/metaseq/optim/fp16_optimizer.py#L452
A similar thing was applied also in the normal FP16Optimizer.
> BF16 bug fix:

- metaseq/distributed/utils.py
Some of our consolidation logic is extremely slow: this is due to the concat's happening on CPU, and the default in pytorch is to use OMP threads to parallelize this. However, we already have spawned multiple processes (or slurm did), so all the threads end up fighting and thrashing for the CPUs.
We could do this individually in every script if we wanted to be careful about optimizing for CPU cases, but given that we basically only ever do GPU logic, we can just bake this assumption right into our distributed code.
Before change, loading checkpoints pegged all CPUs to 100%. After change, they do not and it runs faster.
> [dist] Force threads=1 when spawning.

- cpu_tests/test_jsonl_dataset.py
- metaseq/data/jsonl_dataset.py
There was a performance regression in the JSONL dataset indexer, where when building the index it parsed the jsonl files when it really just needed start-of-line numbers. This was originally done to skip over bad parses.
This PR returns us to the much older behavior of throwing a hard crash, midway during training, when we come to a bad data point. On the positive side, we still report _where_ the file was bad.
We may need to build a separate validator to deal with bad data parses, but at the end of the day, it doesn't feel like "skipping bad data" is the right thing to do.
In progress
> [jsonl] Fix regression in index building.

- metaseq/checkpoint_utils.py
Currently if --restore-file is set, but there's failure in loading the file, we'll (somewhat) silently continue training with a randomly initialized model. This PR makes the failure explicit.
Specifically addresses #142
> Make Checkpoint Loading Strict

- metaseq/checkpoint_utils.py
Fix old checkpoint deletion code to match new naming from https://github.com/facebookresearch/metaseq/commit/6c02d8311f3d7db994d1908edca6096eb99ff16d 
Checked old checkpoints are being deleted now.
> Change deletion of old checkpoints to match new naming

- metaseq/checkpoint_utils.py
- metaseq/dataclass/configs.py
- metaseq/launcher/opt_baselines.py
- metaseq/trainer.py
- metaseq_cli/train.py
Removed most of the no_* and keep_* flags and cleaned up their logic.
I did have some issues with setting up an environment to test this.
In the end I tested with the opt_baselines script and checked if different `save_intervals `and `save_interval_updates ` correctly create all the checkpoints:
`python3 metaseq/launcher/opt_baselines.py --prefix train.8m --model-size 8m --checkpoints-dir ./test-checkpoint --tensorboard-logdir ./test-checkpoint --num-trials 1 --azure --num-gpus 4 --num-nodes 1 --seed 1 --circleci --local --disable-validation --max-epoch 5 --max-update 200`
> Remove no_ and keep_ checkpoint flags

- .github/workflows/lint.yml
- cpu_tests/test_streaming_iterators.py
- cpu_tests/test_streaming_language_modeling_task.py
- metaseq/data/deferred.cpp
- metaseq/data/deferred.py
- metaseq/data/iterators.py
- metaseq/data/streaming_shuffle_dataset.py
- metaseq/data/streaming_token_block_dataset.py
- metaseq/tasks/streaming_language_modeling.py
- pyproject.toml
- setup.py
Introduce machinery to skip ahead in the dataset without having to re-tokenize or read the files in the dataset again. 
Measuring in a separate benchmark script in the internal repo indicates this can run reduce the 'fast-forward' stage of data loader from ~20mins to 14 seconds (around 70x speedup).
This works by storing a cache from document idx -> number of tokens that can be stored in a snapshot as a array of numbers. When the token count is known, the `DeferredDataset` creates `DeferredTensor` objects that know their size, how to compute the value if need and how to generate new tensors via slices and concatenates. Another object `SkipDeferredDataset` skips the first `to_skip` elements, without ever computing the DeferredTensors values, bypassing tokenization …
> [jsonl] Make skipping entries in the dataloader significantly faster

- metaseq/data/deferred.py
@classmethod is needed in newer pytorch versions.
> fix warning

- cpu_tests/test_streaming_iterators.py
- metaseq/data/iterators.py
I misunderstood how the DataLoader worked. I thought it just round-robin each of the workers in turn for the next batch. This is true until one of the workers runs out of batches. At that point it continues by asking other workers for batches until they all ran out. Previously I thought that it would just stop when the first worker ran out. This means that the code was accounting for `sequences_consumed` on each worker inaccurately at the very end of an epoch when some workers have no data.
This is a small patch that fixes the bug and makes it more robust by passing the worker_id to the StreamingCountingIterator instead of having it try to mimic the logic of which worker the batch came from.
> fix bug when counting sequences_consumed near the end of an epoch

- metaseq/checkpoint_utils.py
- metaseq/dataclass/configs.py
- metaseq_cli/train.py
After https://github.com/facebookresearch/metaseq/commit/e3ea5070a8c1bae77703aef7fc0f5537bd437963 we stopped storing checkpoints at the end of the runs. Let's bring them back.
I'm repurposing last_.* checkpoints to be only the ones corresponding to the end of training. In practice, with previous code they were never stored because "epoch" or "updates" one would take precedence. Now, if it's the end of the run and we are not at the end of an epoch or a saving interval, we store the checkpoint using "last_" naming (assuming cfg flag is enabled).
To test: Trained a model and checked that last checkpoint was stored in Azure.
> restore last checkpoint from the end of the training runs

- metaseq/tasks/language_modeling.py
- metaseq/tasks/language_modeling_inference_for_models_trained_with_streaming.py
"prefix_tokens" not used by sequence_generator or sequence_score, inference_step() implementation in lanague_modeling and language_modeling_inference_for_models_trained_with_streaming are the same as the one in base_task. 
> remove deprecated inferencre_step implementation

- metaseq/checkpoint_utils.py
Fix the regex for model loading. Tested with 
```
CUDA_VISIBLE_DEVICES=0,1 FSD=~/data/instruct-opt/prompt_data/allbenchmarks_io_streaming_after_dedup_v5_sorted  python -m metaseq_internal.eval.gpt3_eval --tasks opti
--opti-eval-set test_text_completion__ni_v2__task215_rocstories_incorrect_answer_generation__prompt0  --model-name opt_instr_test  --nb-few-shot-samples-values 0 --distributed-world-size 2 --fsdp --prediction
s-dump-dir ~/del_clf  --n-eval-samples 10
```
Output:
```
Loaded model
model_loading_time=1177.1 seconds
model_loading_time_cuda=1177.1 seconds
Using max-tokens=2048
task=opti
eval_set=test_text_completion__ni_v2__task215_rocstories_incorrect_answer_generation__prompt0
eval language=en
train_set=None
train_lang=None
template=optinstructbenchmark
calibration_options=[] …
```
> Improve regex for model loading

- metaseq/data/jsonl_dataset.py
We've been doing a lot of training on different corpora, and using symbolic links to create the mixture. Because of the way the caching system works, this means we rebuild our line indexes every time we create a new mix of corpora.
This patch builds the indexes next to the original data, not the symlink. This helps re-use indexes across distinct runs.
Been using this for a week plus.
> [jsonl] Re-use caches for symlinks.

- CODEOWNERS
- README.md
Adding @ruanslv as a codeowner to help review PRs.
@urielsinger got swamped with other deadlines, so unfortunately won't be able to take on reviewing work going forward (thanks for being open to doing this before though! ❤️ ).
> Add ruanslv as codeowner

- metaseq/logging/meters.py
- metaseq_cli/train.py
This PR removes state dict of  HistoryMeter so that we do not write log of history information in this meter into checkpoints.
> Meter logging fix

- metaseq/hub_utils.py
Fixes part of https://github.com/facebookresearch/metaseq/issues/383. Model configs without MP don't have "inference" attribute, causing model load to fail with `omegaconf.errors.ConfigAttributeError: Key 'inference' is not in struct`.
"inference" field seems to be used only in MP for the code to track the current status. However, it is always set inside make_generation_fast_() (e.g. https://fburl.com/4gy1ufjv).
So we don't need this line, we can just rely on make_generation_fast_ to set inference to True for us when the model has MP enabled.
Loaded a model with and without MP (1.3B and 350M OPT).
> Fix api model loading for mp=1

- docs/setup.md
Recent changes seemed to break certain combinations fairscale, apex and metaseq.
These are the correct branches that fix [#390](https://github.com/facebookresearch/metaseq/pull/349#issuecomment-1269519987) and https://github.com/facebookresearch/metaseq/issues/390
This also makes the doc and setup here the same.
> Update readme - Add correct fairscale and apex branch

- metaseq_cli/interactive_hosted.py
When you try to run the API service on a slurm node, but you're not inheriting the slurm environment, you get a very strange error:
```
... snip ...
File "/shared/home/dgrnbrg/metaseq/metaseq/checkpoint_utils.py", line 316, in _is_checkpoint_sharded
size_ratio = max(sizes) / min(sizes)
ValueError: max() arg is an empty sequence
```
It turns out this is due to incorrectly inferred config in `metaseq/distributed/utils.py`.
This adds a warning & a sane default (use the entire node that the API server is being run on).
I tried removing each of these env vars, and they're all necessary: any subset causes different crashes.
I ensured I could run & query the API successfully, using the fully sharded 175b param model.
> Set up environment variables for interactive hosted API service

- metaseq/data/iterators.py
This only seems to happen when a job is run locally and the worker threads are launched with 'spawn' instead of 'fork', which is why it wasn't caught earlier.
> fix a bug where collate function can't be pickled

- cpu_tests/test_streaming_iterators.py
- metaseq/data/document_to_sequence.py
- metaseq/tasks/streaming_finetune_language_modeling.py
Training runs using StreamingSrcTgtDataset were failing because they did not do the same token length caching as DocumentsToSequences.
StreamingSrcTgtDataset is really just another instances of StreamingTokenBlockDataset where the the blocks are split into a tuple (src, target). To avoid duplication this PR just adds support for this case directly to DocumentToSequences, and a test to verify this replicates the old behavior.
> Add support for source target style datasets to DocumentToSequence

- metaseq/modules/feedforward_network.py
Fused gelu was unintentionally disabled, but it's been re-enabled after https://github.com/facebookresearch/metaseq/pull/395.
Let's explicitly remove the code for now until we make sure PPL matches regular GeLU.
PS: Fused GeLU is only enabled when bias is present.
> Disable fused gelu until we validate ppl

- metaseq/checkpoint_utils.py
Recent changes to dataloaders have resulted in us creating checkpoint files that are more unequal in size, as shard0 contains the data state. This breaks this older heuristic we used to determine if a checkpoint was Zero2 or Zero3.
This patch changes the heuristic to just read from the config of the file itself.
This patch also gives a better error message for a common mistake.
Internal evaluations.
> [checkpoint] Change logic around is_checkpoint_sharded

- metaseq/data/encoders/hf_byte_bpe.py
- metaseq/sequence_generator.py
While this is simply fixing code we plan to deprecate anyway, I think we need this.
Some of the code paths (namely the generation path for evals) uses this BPE config to instantiate tokenizers. Unfortunately, since this field is missing from the dataclass, it doesn't get populated so when we load up models over there, we can't tell that the tokenizer should be instantiated, and we end up with this hardcoded gpt2 tokenizer path.
This patch fixes that by allowing the tokenizer to load in this BPE class.
Evaluating a model trained with a different tokenizer.
> [inference] Allow non-gpt2 tokenizers in certain code paths.

- metaseq/sequence_generator.py
This assert is incorrect. Temperature = 0.0 is allowed just fine.
Greedy generation in some evals.
> [gen] Fix assert boundary

- metaseq/criterions/cross_entropy.py
- metaseq/model_parallel/criterions/vocab_parallel_cross_entropy.py
- metaseq/models/base_decoder.py
- metaseq/models/base_model.py
- metaseq/models/transformer_decoder.py
- metaseq/models/transformer_encoder.py
* Removed `extract_features_scriptable` from TransformerDecoder
* Removed `get_normalized_probs_scriptable` from BaseModel
* Removed `forward_scriptable` from TransformerEncoder
> [Cleanup] Remove *_scriptable methods

- metaseq_cli/interactive_hosted.py
I noticed the API might be under-batching because we don't correctly detect when a batch might exceed MAX_SEQ_LEN.
Ran the API locally + curl
> Fix the way batch overflow in API requests is detected

- metaseq/model_parallel/modules/multihead_attention.py
- metaseq/model_parallel/modules/transformer_layer.py
- metaseq/models/transformer_decoder.py
- metaseq/models/transformer_encoder.py
- metaseq/modules/multihead_attention.py
- metaseq/modules/transformer_decoder_layer.py
- metaseq/modules/transformer_encoder_layer.py
From MHA, removed the following args:
* `need_head_weights`
* `need_weights`
* `static_kv`
* `before_softmax`
Cleaned up some cluttered returns from MHA (`attn_weights` and `l_aux`).
Follow-up: https://github.com/facebookresearch/metaseq/issues/423
Tested with 2x model parallel 125m, and non-model-parallel 125m.
> [Cleanup] Remove unused args in MHA, cleanup empty returns

- metaseq/cli/README.md
- metaseq/cli/interactive_cli.py
- metaseq/cli/interactive_hosted.py
- metaseq/service/responses.py
`constants.py` needs to be changed for every model configuration. Rather than editing the file in place, this change allows you to _optionally_ export an environment variable `METASEQ_SERVICE_CONSTANTS_MODULE` which is on the python path. When you do this, it will be used for the `interactive_hosted.py` configuration instead.
This allows you to have multiple, local flavors of constants that you can easily refer to.
I made a local override and successfully loaded a model that uses different `LAUNCH_ARGS` than what are commited.
> Add support for constants override

- metaseq/data/document_to_sequence.py
- metaseq/data/jsonl_dataset.py
- metaseq/tasks/base_task.py
- metaseq/trainer.py
Currently there is quite some time between the start of the first train_step and first train_inner log update. This is due to the time it takes for the different processes for each gpu to start. Also it takes some time for each of these processes to completely fill their streaming buffer of training examples. This makes it difficult to debug when something hangs or if there are issues with the data loaders.
To solve this I added some logging to the following:
- once each process starts filling their buffers (this and starting workers takes the most time)
- print out the first batch on the first rank before it enters the model (First point in https://github.com/facebookresearch/metaseq/issues/277)
- Start and finish of the first the forward and backward pass.
This is an example log:
``` …
```
> Add logging to dataloading

- metaseq/launcher/opt_baselines.py
Quick fix to allow users outside of the specified compute envs to specify a data path and avoid the hard coded folder names until we rework the config system.
Solves https://github.com/facebookresearch/metaseq/issues/236
> Allow user to specify external data paths

- metaseq/sequence_generator.py
- metaseq/tasks/base_task.py
Added a new argument to restrict generation to a fixed number of tokens
Tested with 
```
CUDA_VISIBLE_DEVICES=0,1 FSD=/fsx-mudslide/rpasunuru/data/instruct-opt/prompt_data/allbenchmarks_io_streaming_after_dedup_v5_sorted \
python metaseq_internal/scripts/eval/schedule_jobs_few_shot_instruct_opt.py \
-t opti_valid_data_to_text__unified_skg__totto__prompt0 \
-m 1.3B_gptz \
-o /fsx-mudslide/sviyer/tmp_100/ \
--slurm-partition instruct-opt \
--batch-size 8 --override-completed --n-eval-samples 100 --max-gen-tokens 100 --local
```
- Confirmed that it is generating 100 tokens for each example with this argument, and without it, it generates > 1800 tokens per argument.
- Conputed rouge metrics and 
100-tokens = 0.0472
2048 tokens = 0.0047
Also putting out a PR for MSI
> Add argument for max generated tokens

- metaseq/dataclass/utils.py
- metaseq/optim/lr_scheduler/__init__.py
- metaseq/options.py
Removed hacks that turn "fixed" lr_schedule to "inverse_sqrt". These seem to come from the default setting in the scheduler setup. By changing this default to "inverse_sqrt" they are not necessary anymore. I checked internal as well, with its own PR.
Tested with opt_baseline.py and sweep_baseline.py with default settings: The results are the same and the setting for sweep_baseline "polynomial_decay" is correctly propagated and overriding the default.
Issue: https://github.com/facebookresearch/metaseq/issues/434
> remove fixed lr_schedule references

- metaseq_cli/train.py
validate_and_save() already checks for validate_at_beginning, so we don't need this extra call to validate.
See Line 422
> Fix extra valid at beginning

- metaseq/checkpoint_utils.py
Resume on requeue fails right now because we aren't saving checkpoint_last but instead, are saving cherkpoints per interval, like checkpoint_1_600.pt. Commenting this allows resuming even though checkpoint_last isnt saved.
> Resume on requeue

- metaseq/checkpoint_utils.py
I didn't re-run all testing steps from https://github.com/facebookresearch/metaseq/pull/452 and I just caught one case regressed.
Multiple eval runs on OPT 125M:
* remote path + consolidated
* remote path + DP>1
* local path + consolidated
* local path + DP>1
> Return on all matching checkpoint files when caching

- metaseq/checkpoint_utils.py
- metaseq/cli/train.py
- metaseq/dataclass/configs.py
If you set cloud_upload_path to "nfs:<some_local_directory>" this will save the checkpoints to local disk as normal, but then copy to this directory similar to how we do azcopy, except to a local folder mounted in nfs. To avoid many files in the same directory, it adds a directory for each checkpoint. It uses these directories to discover the most recent checkpoint on restart.
Directories are initially created with a leading _ and only renamed when the checkpoint successfully completes.
> Copy to/from NFS with subdirectories.

- metaseq/cli/train.py
Removed previous condition that ensured that we validate everytime we save.
> Only validate at validate_interval_updates and end of training

- metaseq/tasks/streaming_language_modeling.py
When fine-tuning with pre-training data, we need to explicitly set the mix of pre-training data to 0. Otherwise it will be read as a normal task.
> Set pretrain prob to 0 explicitly when it is specified

- metaseq/file_io/common/__init__.py
Addresses #477, and also adds `rename` method to PathManager which is also called in `checkpoint_utils.torch_persistent_save`.
Currently untested, @Xirider should run in his env, as he found the bug.
> Re-add supports_rename and rename to PathManager

- metaseq/checkpoint_utils.py
Currently, num_gpus is set to the local setting of 8, and not the actual number of global gpus. This causes verify-shards to fail and so, resuming from checkpoint fails.
This fixes that
> Fix verify shards - to fix resuming from checkpoint

- metaseq/cli/train.py
From @zdevito: https://discuss.pytorch.org/t/when-i-use-1024-nodes-in-rpc-i-meet-runtimeerror-listen-address-already-in-use/95642 
Removing for now since we don't need to create gloo_pg anymore.
> Remove gloo pg for now, tcp issue

- metaseq/logging/progress_bar/tensorboard_progress_bar.py
Our restart logic is too good these days. Make sure tboard doesn't ever run out of suffixes.
quick job test created the correct tboard folder.
> [tboard] Don't run out of letters

- setup.py
https://pypi.org/project/sklearn/
deprecated sklearn package, use scikit-learn instead
create new env, pip install scikit-learn, create python, import sklearn
> update sklearn package name in setup

- metaseq/checkpoint_utils.py
If we manually pass --reset-dataloader, we need to ignore it after a requeue.
Did not test.
> Don't persist --reset-dataloader past requeues

- metaseq/cli/train.py
- metaseq/data/document_to_sequence.py
- metaseq/data/iterators.py
- metaseq/data/partitioned_streaming_dataset.py
- metaseq/data/streaming_src_tgt_dataset.py
- metaseq/data/streaming_token_block_dataset.py
- metaseq/dataclass/configs.py
- metaseq/logging/progress_bar/tensorboard_progress_bar.py
- metaseq/tasks/base_task.py
- metaseq/tasks/streaming_language_modeling.py
- metaseq/trainer.py
At the moment, we never toggle `train_with_epoch_remainder_batch` anyway - removing this flag for now to reduce surface area here.
> Default to always skip last batch

- metaseq/cli/README.md
- metaseq/cli/interactive_hosted.py
- metaseq/dataclass/configs.py
- metaseq/hub_utils.py
Fixes https://github.com/facebookresearch/metaseq/issues/529, where the problem is very well documented. 
1/ `best_of` should control beam size, while `n` controls number of generations to be returned.
2/ `nbest` doesn't do anything, the number of generations returned is controlled in hub_utils.
> Fixes to generation code (n and best_of params)

- metaseq/checkpoint_utils.py
- metaseq/cli/interactive_cli.py
- metaseq/cli/interactive_hosted.py
- metaseq/hub_utils.py
- metaseq/service/constants.py
1. Support overriding sequence parallelism in the API
2. Support loading FSDP sharded models through the API
1. Take a sequence parallel checkpoint, and create a constants module file (custom_constants_module.py)
```
#
import os
MAX_SEQ_LEN = 2048
BATCH_SIZE = 2048  # silly high bc we dynamically batch by MAX_BATCH_TOKENS
MAX_BATCH_TOKENS = 3072
DEFAULT_PORT = 6010
MODEL_PARALLEL = <REPLACE_MODEL_PARALLEL_SIZE_HERE>
TOTAL_WORLD_SIZE = <REPLACE_WORLD_SIZE_HERE>
MAX_BEAM = 16
CHECKPOINT_FOLDER = <INSERT_MODEL_CHECKPOINT_FOLDER_HERE>
HF_TOKENIZER = <INSERT_TOKENIZER_FILE_HERE>
MODEL_FILE = os.path.join(CHECKPOINT_FOLDER, "reshard.pt")
LAUNCH_ARGS = [
f"--model-parallel-size {MODEL_PARALLEL}",
f"--distributed-world-size {TOTAL_WORLD_SIZE}", …
```
> Support overriding sequence parallelism in the API

- metaseq/dataclass/configs.py
- metaseq/trainer.py
Added a new flag `max_loss_to_skip_batch` that, if set to some maximum acceptable loss will abort the iteration before doing an optimizer step.
The loss value to compare to is the same one used in the logs. It might be or not different to the one in tensorboard.
The logic is similar to our `skip_gradient_update_on_clip_norm` flag which also skips batches, whenever the gradient norm is above the clip value, and also how we handle overflows.
Tested this with our small sweep script. I think our disks are full so I couldn't test this with a longer run.
For testing I increased the loss and checked whether we are skipping correctly
> Automatically detect and skip loss spikes

- metaseq/cli/train.py
In larger runs some dataloaders appear to end early. Adding some debug logging when they reach an end_of_epoch state to try to spot the difference in these instances vs others.
> Debug logging for end_of_epoch

- gpu_tests/test_checkpoint_saving_async.py
previous test_save_checkpoint.py had to test sync saving; this test_save_checkpoint_async.py test checkpoint saving async while saving directly to local (does not skip the async logic)
related to issue https://github.com/facebookresearch/metaseq/issues/516
$ python metaseq/gpu_tests/test_checkpoint_saving_async.py
Ran 1 test in 48.639s
OK
> Fix test checkpoint saving pt2

- metaseq/cli/train.py
- metaseq/dataclass/configs.py
This PR adds the ability to automatically evaluate checkpoints after copying to NFS.
- After the asynchronous copy of a checkpoint to NFS, we check periodically whether all checkpoint parts have finished copying.
- Once all parts are done, we run the eval script defined in `nfs_eval_script_path` for this checkpoint
Add these lines to the internal sweep script to define the eval script path:
https://www.internalfb.com/phabricator/paste/view/P576097431
Testing:
I tested this with a dummy eval script, as the Punit's real eval script should only be used for large runs. I would recommend to check first whether the eval script alone runs correctly on our frozen branch.
> Automatically evaluate checkpoints after copying to NFS

- metaseq/data/indexed_dataset.py
https://numpy.org/doc/stable/user/basics.types.html
https://github.com/numpy/numpy/releases/tag/v1.24.0
This should allow [the GitHub Actions](https://github.com/facebookresearch/metaseq/actions) to pass ✅ 
> numpy.float has been replaced by numpy.single

- docs/api.md
- projects/OPT/download_opt175b.md
I got an email from Meta to download OPT175B weights, and tried to run it by following projects/OPT/download_opt175b.md.
When resharding the shards, I got an error as follows:
```bash
ERROR: The function received no value for the required argument: input_glob_pattern
Usage: reshard_fsdp.py INPUT_GLOB_PATTERN OUTPUT_SHARD_NAME <flags>
optional flags:        --num_output_shards | --unflatten_weights |
--skip_optimizer_state
```
The main reason of this error is lacking the backslash in the scripts. I added it to the scripts as follows:
```bash
for j in {0..7}; do
python -m metaseq.scripts.reshard_fsdp \ # <- I added this backslash
--input-glob-pattern "/groups/gcb50205/actx/opt_175b/checkpoint_last-model_part-$j-shard*.pt" \
--output-shard-name …
```
> Add backslash to the script in projects/OPT/download_opt175b.md

- .flake8
- setup.py
https://github.com/PyCQA/flake8/tags 
`ValueError: Error code '#' supplied to 'extend-ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'`
> Current flake8 no longer accepts comments on config lines

- metaseq/cli/train.py
Due to changes of logic around NFS handling, config.yml is no longer being saved along with training runs. Small hack to fix that.
Launched a 1 node run, validated config.yml exists.
> Fix config.yml dump in training runs.

- .circleci/config.yml
See https://github.com/conda/conda/issues/10431
> Fix circleci: use bash

- projects/OPT/download_opt175b.md
**Summary of Changes**
As mentioned in #590, the recent changes to the FSDP resharding script (see #459) alter the MD5 checksum values when we run it with the options `--skip-optimizer-state True` and `--unflatten-weights True`. We update the doc to be consistent with those changes.
**Test Plan**
The new checksum values are computed using the following command:
```
for j in {0..7}; do md5sum /data/checkpoints/opt-175b/reshard_no_os_unflat/reshard-model_part-$j.pt; done
```
> Update MD5 checkum values of FSDP consolidated shards

- metaseq/distributed/rendezvous.py
- metaseq/distributed/utils.py
Added a barrierlessenv init_method for pytorch distributed method init_process_group. This is done for faster initialization of the process group
Run with --distributed_init_method barrierlessenv://
> barrierless rendezvous for faster init

- README.md
This PR adds the [CTranslate2](https://github.com/OpenNMT/CTranslate2/) integration in the README. CTranslate2 is a fast inference engine for Transformer models, including OPT models.
No tests are needed.
> Community: Add the CTranslate2 integration

- metaseq/dataclass/configs.py
- metaseq/dataclass/constants.py
- metaseq/trainer.py
We've switched to FSDP, so we need to remove the "zero_sharding" code which was predecessor to FSDP. Solving issue #641. 
RN=NB000
python -m PROJECT_NAME.projects.MODEL_NAME.sweep_baseline -g 4 -n 1 --rsc --model-size 8m --tokenizer rsc --prefix $RN --local --data /checkpoint/TEAM_NAME/datasets/consolidated/v4.0
> remove zero_sharding code

- gpu_tests/test_checkpoint_loading_on_more_gpus.py
- metaseq/checkpoint_utils.py
- metaseq/dataclass/configs.py
- metaseq/trainer.py
Enabling checkpoint loading on larger amount of GPUs (following logic from @ngoyal2707 PR #620). Adding test to check if loading from checkpoint created from 2 GPUs possible to start a run on 4 GPUs. Currently we support the case when new number of GPUs is multiple of the previous number of GPUs.
`cd ~/rsc/metaseq`
first run on 2 GPUs and save checkpoint:
`python3 metaseq/launcher/opt_baselines.py --prefix train.8m --model-size 8m --checkpoints-dir ./gpu_tests/test-checkpoint --tensorboard-logdir ./gpu_teststest-checkpoint --num-trials 1    --azure --num-gpus 2 --num-nodes 1 --seed 1 --local --disable-validation --max-epoch 5    --max-update 5 --benchmark`
second run with 4 GPUs and --restore-file from the previous checkpoints:
`python3 …
> load-checkpoint-on-more-gpus

- metaseq/sequence_generator.py
Fix the last step of the decoding process. Specifically in the previous loop using `for step in range(start_step, max_len + 1):`,  when `step = max_len` and iterating to L250 where
```
model_out = self.model.decoder(
tokens[:, : step + 1],
incremental_state=incremental_states,
)
```
error will throw from forward of multihead_attention because tokens is of shape `(bsz * beam_size, max_len)` and when `step=max_len`, `tokens[:, : step + 1]` is of the same shape as `tokens[:, : step]`. This is not usually observed as `max_len` is usually not reached but it’s more easily reached when the input is longer, e.g. in cases when adding long debiasing prefixes. Hence, the loop should be changed to `for step in range(start_step, max_len):` instead.
Specifically errors are
``` …
```
> Fixing the last step of the decoding process

- metaseq/modules/multihead_attention.py
- metaseq/modules/transformer_decoder_layer.py
Model is not correctly initialized if it is consolidated and MP was stitched.
> fix argument passing for consolidated model

- metaseq/cli/train.py
- metaseq/dataclass/configs.py
- metaseq/dataclass/constants.py
- metaseq/trainer.py
See https://github.com/facebookresearch/metaseq/pull/668/
> Uriel's task_ddp_backend setting

- docs/api.md
- metaseq/scripts/reshard_fsdp.py
- metaseq/scripts/reshard_mp.py
- projects/OPT/download_opt175b.md
We add an option to convert weights into a new `dtype` while resharding FSDP checkpoints. This helps reduce checkpoint sizes and avoids issues under RAM constraints when we attempt to load checkpoints. For example, model weights might be saved in full precision but one only needs half precision at inference time.
We also rename some options (e.g. `input-glob-pattern` → `input` and `output-shard-name` → `output`) for succinctness.
* Reshard and convert the OPT-125M checkpoint into various dtypes and make sure we can do inference correctly in the new dtypes:
```
seq 0 1 | parallel --line-buffer 'python metaseq/scripts/reshard_fsdp.py --input "/data/checkpoints/opt-125m/raw/checkpoint_last-model_part-{}-shard*.pt" --output "/data/checkpoints/opt-125m/reshard-no-os/reshard-model_part-{}.pt" …
```
> Add optional type conversion to FSDP resharding script

- metaseq/scripts/convert_to_singleton.py
Adds ability to specify a unified tokenizer file instead of the vocab and merges files.
```
$ wget https://dl.fbaipublicfiles.com/opt/test_artifacts/125m_with_hf_dependencies.tar.gz
$ tar -xvzf 125m_with_hf_dependencies.tar.gz
$ python -m metaseq.scripts.convert_to_singleton 125m
Using unified tokenizer file 125m/gpt2-unified.json                                                                                                                                                   
['--model-parallel-size', '2', '--distributed-world-size', '2', '--ddp-backend', 'pytorch_ddp', '--task', 'language_modeling', '--hf-tokenizer', '125m/gpt2-unified.json', '--bpe', 'hf_byte_bpe', '--
path', '125m/reshard.pt', '--checkpoint-shard-count', '1', …
```
> Adding ability to specify either the unified tokenizer, or the bpe and vocab tokenizer

- gpu_tests/test_checkpoint_saving.py
- metaseq/checkpoint_utils.py
- metaseq/cli/train.py
- metaseq/trainer.py
- tests/test_cli_train.py
Adding back logic that was removed in refactoring (see: https://github.com/facebookresearch/fairseq/blob/0338cdc3094ca7d29ff4d36d64791f7b4e4b5e6e/fairseq/checkpoint_utils.py#L142-L192 and https://github.com/facebookresearch/fairseq/blob/0338cdc3094ca7d29ff4d36d64791f7b4e4b5e6e/fairseq/checkpoint_utils.py#L538-L557) for OG history.
Brought back in by @urielsinger in https://github.com/facebookresearch/metaseq/pull/668.
> Auto-delete checkpoints

- metaseq/scripts/reshard_consolidated.py
- metaseq/scripts/reshard_fsdp.py
- metaseq/scripts/reshard_mp.py
Since the `reshard_mp` script requires FSDP-consolidated checkpoints, we add a new script to support changing FSDP afterwards. By using`reshard_fsdp`, `reshard_mp`, and `reshard_consolidated` together, we are now able to switch from one combination of data parallel and model parallel to another.
* We convert OPT 2.7B checkpoints using the following commands:
```bash
for j in 0 1 2 3; do
python -m metaseq.scripts.reshard_fsdp --input "/checkpoint/binhtang/opt-2.7b/opt-2.7b-raw/checkpoint_last-model_part-$j-shard*.pt" --output "/checkpoint/binhtang/opt-2.7b/opt-2.7b-dp1-mp4/checkpoint_last-model_part-$j-shard{i}.pt" --num-output-shards 1 --unflatten-weights True;
done
python -m metaseq.scripts.reshard_mp --input "/checkpoint/binhtang/opt-2.7b/opt-2.7b-dp1-mp4/checkpoint_last-model_part-*-sha …
```
> Add a script to reshard FSDP-consolidated checkpoints

- metaseq/sequence_generator.py
Currently, `SequenceGenerator` performs forward pass with `self.model.decoder` instead of `self.model`. This doesn't work properly with FSDP, because when wrapped with an FSDP wrapper, `self.model` is a submodule whose sharded parameters aren't all-gathered appropriately during its forward pass, resulting in errors such as the following (see Susan's comment in #698):
```
File "/shared/home/susanz/miniconda3/envs/fairseq-20220503/lib/python3.9/site-packages/torch/nn/functional.py", line 2183, in embedding
return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate …
```
> Support FSDP wrapper in SequenceGenerator

- projects/OPT/assets/opt66b_md5sum_shards.csv
- projects/OPT/download_opt175b.md
Following #698, we need to update the MD5 checksums of consolidated checkpoints for OPT models as `shard_metadata` is added to these checkpoints to aid FSDP conversion. The discrepancy was reported in #702.
> Update MD5 checksums for OPT 66B and OPT 175B checkpoints

- metaseq/benchmark/generator.py
Add a new script to collect latency results for OPT models during generation. While this script resembles the existing one [`metaseq/scripts/generation_benchmarks.py`](https://github.com/facebookresearch/metaseq/pull/240), it's a bit more general where besides latency, we also collect memory usage and GPU traces for various configurations of batch size, input length, and output length. We also use the `GeneratorInterface` directly and skip the checkpoint downloading part.
> Add a script to benchmark generator
